export const SIDEBAR_SUCCESS = 'SIDEBAR_SUCCESS';
export const SIDEBAR_FAILURE = 'SIDEBAR_FAILURE';

export const HOME_SUCCESS = 'HOME_SUCCESS';
export const HOME_FAILURE = 'HOME_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const TRIGGER_LOGGEDIN = 'TRIGGER_LOGGEDIN';
export const TRIGGER_FAILURE = 'TRIGGER_FAILURE';
export const TRIGGER_LOADING = 'TRIGGER_LOADING';

export const SAVE_USER_INFO = 'SAVE_USER_INFO';

export const SEARCH_RESULTS_SUCCESS = 'SEARCH_RESULTS_SUCCESS';
export const SEARCH_RESULTS_FAILURE = 'SEARCH_RESULTS_FAILURE';

export const POST_QUESTION_SUCCESS = 'POST_QUESTION_SUCCESS';
export const POST_QUESTION_INPROGRESS = 'POST_QUESTION_INPROGRESS';

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const GET_PROFILE_QUESTIONS_SUCCESS = 'GET_PROFILE_QUESTIONS_SUCCESS';
export const GET_PROFILE_QUESTIONS_FAILURE = 'GET_PROFILE_QUESTIONS_FAILURE';

export const GET_SINGLE_QUESTION_SUCCESS = 'GET_SINGLE_QUESTION_SUCCESS';
export const GET_SINGLE_QUESTION_FAILURE = 'GET_SINGLE_QUESTION_FAILURE';

export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_INPROGRESS = 'POST_COMMENT_INPROGRESS';
