export const SIDEBAR_SUCCESS = 'SIDEBAR_SUCCESS';
export const SIDEBAR_FAILURE = 'SIDEBAR_FAILURE';

export const HOME_SUCCESS = 'HOME_SUCCESS';
export const HOME_FAILURE = 'HOME_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const TRIGGER_LOGGEDIN = 'TRIGGER_LOGGEDIN';
export const TRIGGER_FAILURE = 'TRIGGER_FAILURE';
export const TRIGGER_LOADING = 'TRIGGER_LOADING';

export const SAVE_USER_INFO = 'SAVE_USER_INFO';

export const SEARCH_RESULTS_SUCCESS = 'SEARCH_RESULTS_SUCCESS';
export const SEARCH_RESULTS_FAILURE = 'SEARCH_RESULTS_FAILURE';
